/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_acs_monitoring_utils_WMI */

#ifndef _Included_ru_acs_monitoring_utils_WMI
#define _Included_ru_acs_monitoring_utils_WMI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_acs_monitoring_utils_WMI
 * Method:    ConnectServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_acs_monitoring_utils_WMI_ConnectServer
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     ru_acs_monitoring_utils_WMI
 * Method:    GetRunningServicesNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_acs_monitoring_utils_WMI_GetRunningServicesNames
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_acs_monitoring_utils_WMI
 * Method:    GetEventLogErrorsCount
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_acs_monitoring_utils_WMI_GetEventLogErrorsCount
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     ru_acs_monitoring_utils_WMI
 * Method:    GetTotalMemorySize
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ru_acs_monitoring_utils_WMI_GetTotalMemorySize
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_acs_monitoring_utils_WMI
 * Method:    GetFreeMemorySize
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ru_acs_monitoring_utils_WMI_GetFreeMemorySize
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_acs_monitoring_utils_WMI
 * Method:    CloseHandle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_acs_monitoring_utils_WMI_CloseHandle
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
