<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by kgn
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:cat_ru="urn:customs.ru:CommonAggregateTypes:5.0.7"
                xmlns:n="urn:customs.ru:Information:ExchangeDocuments:EPS_EvnResponse:5.0.8"
                exclude-result-prefixes="xs xsi xsl"
                xmlns="urn:customs.ru:Information:ExchangeDocuments:EPS_EvnResponse:5.0.8">
    <xsl:namespace-alias stylesheet-prefix="n" result-prefix="#default"/>
    <xsl:output method="xml" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <n:EPS_EnvResponse>
            <xsl:attribute name="xsi:schemaLocation">
                <xsl:value-of select="'urn:customs.ru:Information:ExchangeDocuments:EPS_EvnResponse:5.0.8'"/>
            </xsl:attribute>
            <xsl:variable name="var1_instance" select="."/>
            <xsl:for-each select="$var1_instance/n:EPS_EnvResponse">
                <xsl:attribute name="DocumentModeID">
                    <xsl:value-of select="string(@DocumentModeID)"/>
                </xsl:attribute>
                <cat_ru:DocumentID>
                    <xsl:value-of select="string(cat_ru:DocumentID)"/>
                </cat_ru:DocumentID>
                <xsl:for-each select="cat_ru:RefDocumentID">
                    <cat_ru:RefDocumentID>
                        <xsl:value-of select="string(.)"/>
                    </cat_ru:RefDocumentID>
                </xsl:for-each>
                <n:EnvData/>
            </xsl:for-each>
        </n:EPS_EnvResponse>
    </xsl:template>
</xsl:stylesheet>
