/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_acs_monitoring_utils_ICMP */

#ifndef _Included_ru_acs_monitoring_utils_ICMP
#define _Included_ru_acs_monitoring_utils_ICMP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_acs_monitoring_utils_ICMP
 * Method:    ping
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_ru_acs_monitoring_utils_ICMP_ping
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
